import "./globals.css";
import "swiper/css";
import "swiper/css/bundle";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { Providers } from "./GlobalRedux/provider";
import Nav from "@/components/ui/Nav";
import SessionProvider from "@/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TMDB Next",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Nav />
          <Providers>{children}</Providers>
        </SessionProvider>
      </body>
    </html>
  );
}
